### ISSUE TITLE
Differentiate curtailment by technology

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL/MAGMA#35]
It would be nice to be able to understand the different technologies that are curtailed. So, rather than having a single curtailment number/color, it would be differentiated by technology (e.g. wind-curtailment and solar-curtailment).

**Comment by jnovache** [comment]
I know in the past we've been hesitant about reporting technology specific curtailment since they are both zero cost resources and you might encounter a degeneracy problem. So it may be misleading to report one technology being curtailed while the other isn't. Of course if it's curtailment at night or in a region with no wind installed that's a different story.

**Comment by claytonpbarrows** [comment]
I agree with your concerns, but could make the same argument for any dispatch reduction for any generator. I'd likely not report it in a final graphic or a study report, but for debugging and an intermediate solution summary, it can be useful. 
The flexibility to aggregate curtailment or not should be part of the feature.

**Comment by bradystoll** [comment]
Added two plots to differentiate curtailment by technology type in bcdbd86cacb193068c3df5ffd031e089e34aa256
