### ISSUE TITLE
check for any unused functions and remove

### ISSUE THREAD

**Issue by oconnellm** [NREL/MAGMA#76]

**Comment by oconnellm** [comment]
seems like region load is queried multiple times. Maybe we can clean up the queries so that we aren't doing unnecessary steps? I know a lot of the comparison sections call query functions again but if the comparison section is running it means the original part already did the query and we can probably just use that data instead of calling the function again....? Just a thought

**Comment by bradystoll** [comment]
Like the rplexos query happens multiple times? That probably shouldn't happen. I actually tried to get rid of all of the "if exists()" statements that create variables, because sometimes that variable was getting changed later, or if you re-ran the code with different scenarios it wasn't updating. The code is fast enough now that I think re-running the functions that manipulate data should be fine
